openapi: 3.0.3
info:
  title: OpenLigaDB
  version: 0.0.1
servers:
  - url: https://www.openligadb.de/api

paths:
  /getmatchdata/{liga}/{year}:
    get:
      operationId: getMatchsByLigaAndYear
      parameters:
        - name: liga
          in: path
          required: true
          schema:
            type: string
        - name: year
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Get matches by liga and year
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'

  /getmatchdata/{id}:
    get:
      operationId: getMatch
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Get match
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Match'

components:
  schemas:
    Group:
      properties:
        GroupName:
          type: string
      required:
        - GroupName
    Team:
      properties:
        TeamName:
          type: string
        ShortName:
          type: string
        TeamIconUrl:
          type: string
          format: uri
      required:
        - TeamName
    Result:
      properties:
        ResultName:
          type: string
        PointsTeam1:
          type: integer
        PointsTeam2:
          type: integer
        ResultTypeID:
          type: integer
      required:
        - PointsTeam1
        - PointsTeam2
        - ResultTypeID
    Location:
      properties:
        LocationCity:
          type: string
        LocationStadium:
          type: string
    Match:
      properties:
        MatchID:
          type: integer
        MatchDateTimeUTC:
          type: string
          format: date-time
        LeagueName:
          type: string
        MatchIsFinished:
          type: boolean
        Group:
          $ref: '#/components/schemas/Group'
        Team1:
          $ref: '#/components/schemas/Team'
        Team2:
          $ref: '#/components/schemas/Team'
        MatchResults:
          type: array
          items:
            $ref: '#/components/schemas/Result'
        Location:
          $ref: '#/components/schemas/Team'
      required:
        - MatchID